/**
 * Security primitives for Mooday's app-lock feature.
 *
 * Two complementary unlock mechanisms are supported:
 *
 * 1. **PIN** — a numeric fallback. The PIN is never stored in cleartext.
 *    We derive a 256-bit key with PBKDF2-SHA-256 (>=120k iterations) using
 *    a per-user random salt, then store the salt + base64(hash) in
 *    localStorage. Verification recomputes the hash and constant-time
 *    compares against the stored value.
 *
 * 2. **Biometric / passkey (WebAuthn)** — `navigator.credentials.create`
 *    and `navigator.credentials.get`. The private key never leaves the
 *    device's authenticator (Touch ID, Face ID, Windows Hello, Android
 *    fingerprint, etc.). We persist the credential id so subsequent
 *    unlocks can look it up; the public key is regenerated by the
 *    platform during assertion.
 *
 * Both methods are completely client-side. Mooday's threat model for
 * this layer is *casual device snooping* (a friend picks up an
 * unlocked phone), not a determined attacker with local code-execution.
 * Server-side auth still happens via the existing Phase 2 backend; the
 * app-lock just hides the UI until the local factor succeeds.
 */

const PBKDF2_ITERATIONS = 120_000;
const PBKDF2_HASH = "SHA-256";
const PBKDF2_KEY_BITS = 256;

export const LOCK_STORAGE_KEYS = {
  enabled: "mooday_lock_enabled",
  timeoutMs: "mooday_lock_timeout_ms",
  pinHash: "mooday_lock_pin_hash",
  pinSalt: "mooday_lock_pin_salt",
  webauthnCredentialId: "mooday_lock_webauthn_cred_id",
} as const;

/** Allowed lock timeouts (in milliseconds). Mirrors the Settings UI. */
export const LOCK_TIMEOUT_PRESETS_MS = [
  60_000, // 1 minute
  5 * 60_000, // 5 minutes
  15 * 60_000, // 15 minutes
  30 * 60_000, // 30 minutes
  60 * 60_000, // 1 hour
] as const;

export type LockTimeoutMs = (typeof LOCK_TIMEOUT_PRESETS_MS)[number];

export const DEFAULT_LOCK_TIMEOUT_MS: LockTimeoutMs = 5 * 60_000;

// ---------------------------------------------------------------------------
// PIN hashing
// ---------------------------------------------------------------------------

function getSubtleCrypto(): SubtleCrypto | null {
  if (typeof window === "undefined") return null;
  // window.crypto?.subtle is missing on insecure origins (http://) and in
  // some test runners, so we degrade gracefully instead of throwing.
  return window.crypto?.subtle ?? null;
}

function bytesToBase64(bytes: Uint8Array): string {
  let s = "";
  for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s);
}

function base64ToBytes(b64: string): Uint8Array {
  const s = atob(b64);
  // Allocate via ArrayBuffer explicitly so the underlying buffer is
  // `ArrayBuffer` (never `SharedArrayBuffer`). Recent TS lib.dom
  // types tightened `BufferSource` to `ArrayBufferView<ArrayBuffer>`
  // and the random values path below produces a Uint8Array that the
  // WebCrypto API rejects when its buffer is generic.
  const out = new Uint8Array(new ArrayBuffer(s.length));
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
  return out;
}

/**
 * Hash a PIN with PBKDF2. Returns `{ salt, hash }` both base64-encoded
 * for safe storage. Salt is freshly generated on every call so the same
 * PIN produces a different hash each time it is set.
 */
export async function hashPin(
  pin: string,
): Promise<{ salt: string; hash: string } | null> {
  const subtle = getSubtleCrypto();
  if (!subtle) return null;
  const enc = new TextEncoder();
  const saltBytes = window.crypto.getRandomValues(newUint8Array(16));
  const keyMaterial = await subtle.importKey(
    "raw",
    enc.encode(pin),
    { name: "PBKDF2" },
    false,
    ["deriveBits"],
  );
  const bits = await subtle.deriveBits(
    {
      name: "PBKDF2",
      salt: saltBytes as BufferSource,
      iterations: PBKDF2_ITERATIONS,
      hash: PBKDF2_HASH,
    },
    keyMaterial,
    PBKDF2_KEY_BITS,
  );
  return {
    salt: bytesToBase64(saltBytes),
    hash: bytesToBase64(new Uint8Array(bits)),
  };
}

/**
 * Constant-time comparison of two base64-encoded hashes. Avoids leaking
 * length or prefix-match information via timing.
 */
function constantTimeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

/** Returns true if `pin` matches the stored hash for `saltB64`. */
export async function verifyPin(
  pin: string,
  saltB64: string,
  hashB64: string,
): Promise<boolean> {
  const subtle = getSubtleCrypto();
  if (!subtle) return false;
  const enc = new TextEncoder();
  const saltBytes = base64ToBytes(saltB64);
  const keyMaterial = await subtle.importKey(
    "raw",
    enc.encode(pin),
    { name: "PBKDF2" },
    false,
    ["deriveBits"],
  );
  const bits = await subtle.deriveBits(
    {
      name: "PBKDF2",
      salt: saltBytes as BufferSource,
      iterations: PBKDF2_ITERATIONS,
      hash: PBKDF2_HASH,
    },
    keyMaterial,
    PBKDF2_KEY_BITS,
  );
  const candidate = bytesToBase64(new Uint8Array(bits));
  return constantTimeEqual(candidate, hashB64);
}

// ---------------------------------------------------------------------------
// WebAuthn / biometric
// ---------------------------------------------------------------------------

export interface WebAuthnSupport {
  /** navigator.credentials.create / .get exist. */
  available: boolean;
  /**
   * Whether the platform advertises an attached authenticator (Touch ID,
   * Face ID, Windows Hello, Android fingerprint, etc.). We surface this
   * in the UI to decide whether to show the "use biometric" toggle.
   *
   * Note: `PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable`
   * is the official signal. We assume false if the API itself is missing.
   */
  hasPlatformAuthenticator: boolean;
}

export async function detectWebAuthnSupport(): Promise<WebAuthnSupport> {
  if (typeof window === "undefined") {
    return { available: false, hasPlatformAuthenticator: false };
  }
  const ctor = window.PublicKeyCredential;
  if (!ctor || !window.navigator?.credentials?.create) {
    return { available: false, hasPlatformAuthenticator: false };
  }
  let hasPlatform = false;
  try {
    hasPlatform = await ctor.isUserVerifyingPlatformAuthenticatorAvailable();
  } catch {
    hasPlatform = false;
  }
  return { available: true, hasPlatformAuthenticator: hasPlatform };
}

/** Prefer the registrable domain in production; localhost during dev. */
function getRpId(): string | undefined {
  if (typeof window === "undefined") return undefined;
  const { hostname } = window.location;
  if (hostname === "localhost" || hostname === "127.0.0.1") return undefined;
  return hostname;
}

function randomChallenge(): Uint8Array<ArrayBuffer> {
  return window.crypto.getRandomValues(newUint8Array(32));
}

/**
 * Allocate a Uint8Array explicitly backed by an `ArrayBuffer`. Some
 * WebCrypto APIs in current TS lib.dom types require `BufferSource`
 * whose view is `ArrayBufferView<ArrayBuffer>` (not the more permissive
 * `ArrayBufferLike` which covers `SharedArrayBuffer`). Without this
 * helper the compiler infers a buffer of `ArrayBufferLike` and rejects
 * the assignment at the call site.
 */
function newUint8Array(length: number): Uint8Array<ArrayBuffer> {
  return new Uint8Array(new ArrayBuffer(length));
}

function bufferToBase64Url(buf: ArrayBuffer): string {
  const bytes = new Uint8Array(buf);
  let s = "";
  for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

/**
 * Register a passkey tied to Mooday. The credential id is stored so
 * `verifyBiometric` can target it later. Throws on user cancellation
 * (`NotAllowedError`) or platform rejection so the caller can show an
 * error and let the user try again.
 */
export async function registerBiometric(userName: string): Promise<string> {
  if (typeof window === "undefined" || !window.navigator?.credentials?.create) {
    throw new Error("Biometric authentication is not available on this device.");
  }
  const credential = (await window.navigator.credentials.create({
    publicKey: {
      challenge: randomChallenge(),
      rp: {
        name: "Mooday",
        id: getRpId(),
      },
      user: {
        id: newUint8Array(16) as BufferSource,
        name: userName || "Mooday user",
        displayName: userName || "Mooday user",
      },
      pubKeyCredParams: [
        { type: "public-key", alg: -7 }, // ES256
      ],
      authenticatorSelection: {
        authenticatorAttachment: "platform",
        residentKey: "preferred",
        userVerification: "required",
      },
      timeout: 60_000,
      attestation: "none",
    },
  })) as PublicKeyCredential | null;
  if (!credential) {
    throw new Error("Biometric setup was cancelled.");
  }
  return bufferToBase64Url(credential.rawId);
}

/**
 * Prompt the platform authenticator (Touch ID / Face ID / fingerprint /
 * Windows Hello) for the credential stored under `credentialIdB64Url`.
 * Resolves true on success, false on user cancellation / no match.
 */
export async function verifyBiometric(
  credentialIdB64Url: string,
): Promise<boolean> {
  if (typeof window === "undefined" || !window.navigator?.credentials?.get) {
    return false;
  }
  const credIdBytes = Uint8Array.from(
    atob(credentialIdB64Url.replace(/-/g, "+").replace(/_/g, "/")),
    (c) => c.charCodeAt(0),
  );
  // Uint8Array.from can produce a Uint8Array backed by SharedArrayBuffer
  // when TS infers the result type. Copy into a fresh ArrayBuffer-backed
  // view so WebAuthn accepts it.
  const credIdBuffer: Uint8Array<ArrayBuffer> = new Uint8Array(
    new ArrayBuffer(credIdBytes.length),
  );
  credIdBuffer.set(credIdBytes);
  try {
    const assertion = (await window.navigator.credentials.get({
      publicKey: {
        challenge: randomChallenge(),
        allowCredentials: [
          {
            id: credIdBuffer as BufferSource,
            type: "public-key",
            transports: ["internal"],
          },
        ],
        userVerification: "required",
        timeout: 60_000,
      },
    })) as PublicKeyCredential | null;
    return Boolean(assertion);
  } catch {
    // NotAllowedError = user dismissed prompt; treat as failure, not throw.
    return false;
  }
}

export function getLockTimeout(): LockTimeoutMs {
  try {
    const val = localStorage.getItem(LOCK_STORAGE_KEYS.timeoutMs);
    if (val) {
      const parsed = parseInt(val, 10);
      if (!isNaN(parsed) && LOCK_TIMEOUT_PRESETS_MS.includes(parsed as LockTimeoutMs)) {
        return parsed as LockTimeoutMs;
      }
    }
  } catch {
    // Ignore storage errors
  }
  return DEFAULT_LOCK_TIMEOUT_MS;
}
