awk '
BEGIN { inserted = 0 }
/-- ---------- audit log ----------/ && !inserted {
  print "-- Add a trigger to prevent non-admins from modifying admin fields via RLS "
  print "create or replace function public.check_profile_admin_update()"
  print "returns trigger as $$"
  print "declare"
  print "  is_admin_actor boolean;"
  print "  current_uid uuid;"
  print "begin"
  print "  if new.is_admin = old.is_admin "
  print "     and new.is_suspended = old.is_suspended "
  print "     and new.suspended_reason is not distinct from old.suspended_reason"
  print "     and new.suspended_at is not distinct from old.suspended_at"
  print "  then"
  print "    return new;"
  print "  end if;"
  print ""
  print "  current_uid := auth.uid();"
  print "  if current_uid is not null then"
  print "    if current_uid = old.id then"
  print "      is_admin_actor := old.is_admin;"
  print "    else"
  print "      select is_admin into is_admin_actor"
  print "      from public.profiles"
  print "      where id = current_uid;"
  print "    end if;"
  print ""
  print "    if not coalesce(is_admin_actor, false) then"
  print "      raise exception using errcode = '\''insufficient_privilege'\'', message = '\''a non-admin user cannot flip their own is_admin flag'\'';"
  print "    end if;"
  print "  end if;"
  print ""
  print "  return new;"
  print "end;"
  print "$$ language plpgsql security definer;"
  print ""
  print "drop trigger if exists enforce_profile_admin_update on public.profiles;"
  print "create trigger enforce_profile_admin_update"
  print "  before update on public.profiles"
  print "  for each row"
  print "  execute function public.check_profile_admin_update();"
  print ""
  inserted = 1
}
{ print }
' supabase/migrations/202607150008_phase_3_5_admin.sql > tmp.sql && mv tmp.sql supabase/migrations/202607150008_phase_3_5_admin.sql
