import { PHONE_PLACEHOLDER } from "@/lib/constants";
import type { CheckoutCopy } from "./types";

export const COPY: Record<"en" | "ar", CheckoutCopy> = {
  en: {
    pageTitle: "Checkout",
    stepAddress: "Shipping",
    stepPayment: "Payment",
    savedAddresses: "Saved addresses",
    useDifferent: "Use a different address",
    newAddressTitle: "New delivery address",
    addNewAddress: "+ Add a new address",
    fullName: "Full name",
    fullNamePh: "Enter your full name",
    phone: "Phone number",
    phonePh: PHONE_PLACEHOLDER,
    city: "City",
    street: "Street, building, apartment",
    streetPh: "e.g. Villa 24, Al Wasl Road",
    districtLabel: "District / area",
    districtPh: "e.g. Jumeirah",
    notesLabel: "Delivery notes (optional)",
    notesPh: "Landmark, gate, etc.",
    proceedToPayment: "Continue to payment",
    errorRequired: "Please complete the required fields.",
    savedCards: "Saved cards",
    addNewCard: "+ Add a new card",
    newCardTitle: "New card",
    cardNumber: "Card number",
    cardHolder: "Cardholder name",
    expiry: "Expiry",
    cvv: "CVV",
    applePayLabel: "Apple Pay",
    applePayBody: "One-tap payment via Apple Pay.",
    codLabel: "Cash on Delivery",
    codBody: "Pay in cash when your order arrives.",
    codUnavailable: "Cash on Delivery is unavailable for orders over AED 5,000.",
    secureCheckoutAed: (n) => `Secure checkout (AED ${n})`,
    processing: "Securing escrow payment...",
    orderReview: "Order review",
    qty: (n) => `Qty: ${n}`,
    subtotal: "Subtotal",
    shipping: "Shipping (Mooday Express)",
    shippingFree: "FREE",
    total: "Total",
    defaultBadge: "Default",
    backToHome: "Back to home",
    orderPlaced: "Order placed",
    escrowBody:
      "Your payment has been secured in Mooday's Escrow vault. Funds will only be released to the seller after you receive the item and confirm it matches the description.",
    emptyTitle: "Your bag is empty",
    emptyBody: "Add something you love before checking out.",
    emptyBack: "Back to shopping",
  },
  ar: {
    pageTitle: "إتمام الشراء",
    stepAddress: "العنوان",
    stepPayment: "الدفع",
    savedAddresses: "العناوين المحفوظة",
    useDifferent: "استخدام عنوان آخر",
    newAddressTitle: "عنوان جديد",
    addNewAddress: "+ إضافة عنوان",
    fullName: "الاسم الكامل",
    fullNamePh: "ادخل اسمك",
    phone: "رقم الهاتف",
    phonePh: PHONE_PLACEHOLDER,
    city: "الإمارة",
    street: "الشارع، المبنى، الشقة",
    streetPh: "مثال: فيلا 24، شارع الوصل",
    districtLabel: "المنطقة",
    districtPh: "مثال: جميرا",
    notesLabel: "ملاحظات التوصيل (اختياري)",
    notesPh: "معلم قريب، البوابة...",
    proceedToPayment: "الذهاب للدفع",
    errorRequired: "يرجى إكمال الحقول المطلوبة.",
    savedCards: "البطاقات المحفوظة",
    addNewCard: "+ إضافة بطاقة",
    newCardTitle: "بطاقة جديدة",
    cardNumber: "رقم البطاقة",
    cardHolder: "الاسم على البطاقة",
    expiry: "تاريخ الانتهاء",
    cvv: "CVV",
    applePayLabel: "Apple Pay",
    applePayBody: "الدفع بنقرة واحدة عبر Apple Pay.",
    codLabel: "الدفع عند الاستلام",
    codBody: "ادفع نقداً عند استلام طلبك.",
    codUnavailable: "الدفع عند الاستلام غير متاح للطلبات التي تتجاوز ٥٬٠٠٠ درهم.",
    secureCheckoutAed: (n) => `إتمام الدفع (AED ${n})`,
    processing: "جاري تأمين المبلغ...",
    orderReview: "مراجعة الطلب",
    qty: (n) => `الكمية: ${n}`,
    subtotal: "المجموع الفرعي",
    shipping: "الشحن (مودي إكسبرس)",
    shippingFree: "مجاني",
    total: "الإجمالي",
    defaultBadge: "افتراضي",
    backToHome: "العودة للرئيسية",
    orderPlaced: "تم تسجيل الطلب",
    escrowBody:
      "تم تأمين المبلغ في حساب مودي. لن يتم تسليم المبلغ للبائع إلا بعد استلامك للطلب وتأكيد مطابقته للوصف.",
    emptyTitle: "حقيبتك فارغة",
    emptyBody: "أضيفي شيئاً تحبينه قبل إتمام الشراء.",
    emptyBack: "العودة للتسوق",
  },
};

export const CITIES_EN = [
  "Dubai",
  "Abu Dhabi",
  "Sharjah",
  "Ajman",
  "Ras Al Khaimah",
  "Fujairah",
  "Umm Al Quwain",
];

export const CITIES_AR = [
  "دبي",
  "أبوظبي",
  "الشارقة",
  "عجمان",
  "رأس الخيمة",
  "الفجيرة",
  "أم القيوين",
];
