export interface CheckoutCopy {
  pageTitle: string;
  stepAddress: string;
  stepPayment: string;
  savedAddresses: string;
  useDifferent: string;
  newAddressTitle: string;
  addNewAddress: string;
  fullName: string;
  fullNamePh: string;
  phone: string;
  phonePh: string;
  city: string;
  street: string;
  streetPh: string;
  districtLabel: string;
  districtPh: string;
  notesLabel: string;
  notesPh: string;
  proceedToPayment: string;
  errorRequired: string;
  savedCards: string;
  addNewCard: string;
  newCardTitle: string;
  cardNumber: string;
  cardHolder: string;
  expiry: string;
  cvv: string;
  applePayLabel: string;
  applePayBody: string;
  codLabel: string;
  codBody: string;
  codUnavailable: string;
  secureCheckoutAed: (n: number) => string;
  processing: string;
  orderReview: string;
  qty: (n: number) => string;
  subtotal: string;
  shipping: string;
  shippingFree: string;
  total: string;
  defaultBadge: string;
  backToHome: string;
  orderPlaced: string;
  escrowBody: string;
  emptyTitle: string;
  emptyBody: string;
  emptyBack: string;
}

export type PaymentChoice = "saved-card" | "new-card" | "apple" | "cod";
