import type { Metadata, Viewport } from "next";
import { headers } from "next/headers";
import { Hanken_Grotesk, Bodoni_Moda, Noto_Sans_Arabic, El_Messiri } from "next/font/google";
import { AppProvider } from "@/context/AppContext";
import { ServiceWorkerRegistrar } from "@/components/ServiceWorkerRegistrar";
import { ThemeSync } from "@/components/ThemeSync";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { BRAND, BRAND_AR, BRAND_TAGLINE_EN, BRAND_TAGLINE_AR } from "@/lib/brand";
import "./globals.css";

const hankenGrotesk = Hanken_Grotesk({
  variable: "--font-family-sans-en",
  subsets: ["latin"],
  display: "swap",
});

const bodoniModa = Bodoni_Moda({
  variable: "--font-family-serif-en",
  subsets: ["latin"],
  display: "swap",
});

const notoSansArabic = Noto_Sans_Arabic({
  variable: "--font-family-sans-ar",
  subsets: ["arabic"],
  display: "swap",
});

const elMessiri = El_Messiri({
  variable: "--font-family-serif-ar",
  subsets: ["arabic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: `${BRAND} - ${BRAND_TAGLINE_EN}`,
    template: `%s | ${BRAND}`,
  },
  description: `${BRAND_AR} | ${BRAND_TAGLINE_EN} ${BRAND_TAGLINE_AR}`,
  applicationName: BRAND,
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: BRAND,
    startupImage: [
      // iPhone 14 Pro Max, 15 Pro Max
      {
        url: "/icons/apple-touch-icon.png",
        media: "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)",
      },
    ],
  },
  formatDetection: {
    telephone: false,
  },
  icons: {
    icon: [
      { url: "/icons/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/icons/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/icon-192x192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512x512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
    other: [
      {
        rel: "mask-icon",
        url: "/icons/icon-maskable-512x512.png",
        color: "#F9A11B",
      },
    ],
  },
  other: {
    "mobile-web-app-capable": "yes",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "default",
    "apple-mobile-web-app-title": BRAND,
    "msapplication-TileColor": "#F9A11B",
    "msapplication-TileImage": "/icons/icon-512x512.png",
    "msapplication-config": "none",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1.0,
  maximumScale: 1.0,
  userScalable: false,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#F9A11B" },
    { media: "(prefers-color-scheme: dark)", color: "#7a5a0c" },
  ],
  colorScheme: "light dark",
};

// A request nonce is generated by `src/proxy.ts`. The root layout must stay
// dynamic so Next.js can attach that nonce to its script tags.
export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const requestHeaders = await headers();
  const language = requestHeaders.get("x-daneg-language") === "ar" ? "ar" : "en";

  return (
    <html
      lang={language}
      dir={language === "ar" ? "rtl" : "ltr"}
      suppressHydrationWarning
      className={`${hankenGrotesk.variable} ${bodoniModa.variable} ${notoSansArabic.variable} ${elMessiri.variable} h-full antialiased`}
    >
      <head>
        {/* eslint-disable-next-line @next/next/no-page-custom-font -- Material Symbols is a shared icon font used by the app shell. */}
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-full flex flex-col">
        <ThemeSync />
        <AppProvider>
          <ErrorBoundary>
            <ServiceWorkerRegistrar />
            {children}
          </ErrorBoundary>
        </AppProvider>
      </body>
    </html>
  );
}
