// Dynamic sitemap — generated by Next.js at request time.
// Lists the marketing landing in both languages. The /app SPA shell is
// excluded (see robots.txt) to keep the index clean.

import type { MetadataRoute } from "next";
import { COPY } from "@/components/landing/copy";
import { LEGAL_DOCUMENTS } from "@/app/legal/content";
import { CANONICAL_SITE_URL } from "@/lib/feature-flags";

const SITE_URL = CANONICAL_SITE_URL;

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  // Re-use the canonical headlines so the <title> hierarchy stays aligned.
  // (The landing copy is mirrored in /src/components/landing/copy.ts.)
  void COPY;

  return [
    {
      url: `${SITE_URL}/`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 1,
      alternates: {
        languages: {
          en: `${SITE_URL}/`,
          ar: `${SITE_URL}/?lang=ar`,
          "x-default": `${SITE_URL}/`,
        },
      },
    },
    // The legal documents are indexable on purpose: payment providers and
    // app stores require a publicly reachable URL for each one.
    ...LEGAL_DOCUMENTS.map((doc) => ({
      url: `${SITE_URL}/legal/${doc.slug}`,
      lastModified: now,
      changeFrequency: "yearly" as const,
      priority: 0.3,
    })),
  ];
}
