export const COPY = {
  en: {
    back: "Back",
    searchPlaceholder: "Search for bags, dresses, decor...",
    search: "Search",
    clearSearch: "Clear search",
    filters: "Filters",
    showFilters: "Show filters",
    hideFilters: "Hide filters",
    categories: "Categories",
    condition: "Item Condition",
    size: "Size",
    colour: "Colour",
    priceRange: "Price Range",
    minPrice: "Min",
    maxPrice: "Max",
    listingMode: "Listing Mode",
    all: "All",
    resell: "Resell",
    rent: "Rent",
    rentComingSoon: "Coming soon",
    sortBy: "Sort by",
    relevance: "Relevance",
    newest: "Newest",
    priceLow: "Price: Low to High",
    priceHigh: "Price: High to Low",
    found: (n: number) => `Found ${n} item${n === 1 ? "" : "s"}`,
    noResults: "We couldn't find any items matching your search.",
    clearAll: "Clear all filters",
    apply: "Apply",
    price: "Price",
  },
  ar: {
    back: "رجوع",
    searchPlaceholder: "ابحث عن حقيبة، فستان، ديكور...",
    search: "بحث",
    clearSearch: "مسح البحث",
    filters: "الفلاتر",
    showFilters: "عرض الفلاتر",
    hideFilters: "إخفاء الفلاتر",
    categories: "الفئات",
    condition: "حالة المنتج",
    size: "المقاس",
    colour: "اللون",
    priceRange: "نطاق السعر",
    minPrice: "أقل",
    maxPrice: "أعلى",
    listingMode: "نوع العرض",
    all: "الكل",
    resell: "بيع",
    rent: "إيجار",
    rentComingSoon: "قريباً",
    sortBy: "ترتيب حسب",
    relevance: "الصلة",
    newest: "الأحدث",
    priceLow: "السعر: من الأقل إلى الأعلى",
    priceHigh: "السعر: من الأعلى إلى الأقل",
    found: (n: number) => `تم العثور على ${n} منتج`,
    noResults: "لم نجد أي منتجات تطابق بحثك.",
    clearAll: "مسح كل الفلاتر",
    apply: "تطبيق",
    price: "السعر",
  },
} as const;
